---
env:
  contexts:
  - name: "selenium-auth"
    urls:
    - "https://pp-services.signin.education.gov.uk/"
    includePaths:
    - "https://pp-services.signin.education.gov.uk/.*"
    excludePaths: []
    authentication:
      method: "script"
      parameters:
        script: "/zap/wrk/kotlin_external.kts"
        scriptEngine: "kotlin"
        cookie_file: "cookies.txt"
        auth_script_file: "/zap/wrk/selenium_login.py"
        test_path: "https://pp-services.signin.education.gov.uk/my-services"
      verification:
        method: "poll"
        loggedInRegex: ".*Access DfE services.*"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: "https://pp-services.signin.education.gov.uk/my-services"
        pollPostData: ""
    sessionManagement:
      method: "script"
      parameters:
        script: "/zap/wrk/session.js"
        scriptEngine: "Oracle Nashorn"
    technology:
      exclude: []
    users:
    - name: "test"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    action: "add"
    type: "httpsender"
    engine: "Oracle Nashorn"
    name: "LogMessages.js"
    file: "/zap/wrk/LogMessages.js"
  name: "script"
  type: "script"
