---
name: Test Zap
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  scan:

    permissions:
      security-events: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: ZAP Scan
        uses: zaproxy/action-af@v0.1.0
        with:
          plan: 'test-plan.yml'
          cmd_options: '-addoninstall kotlin -loglevel debug'
          docker_env_vars: |
            USER
            PASSWORD
        env:
          USER: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Upload logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: "logs"
          path: "${{ github.workspace }}/req-resp-log.txt"
          retention-days: 1
            
