---
name: Test Nuclei

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
  
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
    
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install GoSpider
        run: |
          GO111MODULE=on go install github.com/jaeles-project/gospider@latest

      - name: Run selenium
        env:
          USER: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python selenium_login.py dfe-login

      - name: Run GoSpider
        run: |
          python selenium_login.py spider

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: "${{ github.workspace }}/urls.txt"
          flags: "-sf ${{ github.workspace }}/secrets.yaml"
          sarif-export: "${{ github.workspace }}/dfe_login.sarif"

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "${{ github.workspace }}/dfe_login.sarif"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            